gpaket_homepage:
    path:     /
    defaults: { _controller: GpaketBundle:Default:index }
telegram_ep:
    path:     /telegram/
    defaults: { _controller: GpaketBundle:Telegram:index }
telegram_setHook:
    path:     /panel/telegram/setHook
    defaults: { _controller: GpaketBundle:Telegram:setHook }
telegram_sendAoe:
    path:     /panel/telegram/sendAoe
    defaults: { _controller: GpaketBundle:Telegram:sendAoe }
telegram_ajaxCounter:
    path:     /ajax/{entity}/
    defaults: { _controller: GpaketBundle:Default:getCount }
_sonata_admin:
    prefix: /panel
    resource: /panel/
    type: sonata_admin