gpaket_homepage:
    path:     /
    defaults: { _controller: GpaketBundle:Default:index }
telegram_ep:
    path:     /telegram/
    defaults: { _controller: GpaketBundle:Telegram:index }
telegram_setHook:
    path:     /panel/telegram/setHook
    defaults: { _controller: GpaketBundle:Telegram:setHook }