services:
    gpaket.admin.config:
        class: GpaketBundle\Admin\ConfigAdmin
        arguments: [~, GpaketBundle\Entity\Config, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Config }
