GpaketBundle\Entity\Chat:
    type: entity
    table: null
    repositoryClass: GpaketBundle\Repository\ChatRepository
    id:
        chat_id:
            type: bigint
            id: true
    fields:
        title:
            type: string
            nullable: true
            length: 255
        username:
            type: string
            nullable: true
            length: 255
        type:
            type: string
            nullable: true
            length: 255
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: chat
    lifecycleCallbacks: {  }
