GpaketBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: GpaketBundle\Repository\UserRepository
    id:
        user_id:
            type: integer
            id: true
    fields:
        first_name:
            type: string
            nullable: true
            length: 255
        last_name:
            type: string
            nullable: true
            length: 255
        username:
            type: string
            nullable: true
            length: 255
        usernameCanonical:
            column: username_canonical
            type: string
            length: 180
        email:
            column: email
            type: string
            length: 180
        emailCanonical:
            column: email_canonical
            type: string
            length: 180
        enabled:
            column: enabled
            type: boolean
        salt:
            column: salt
            type: string
        password:
            column: password
            type: string
        lastLogin:
            column: last_login
            type: datetime
            nullable: true
        locked:
            column: locked
            type: boolean
        expired:
            column: expired
            type: boolean
        expiresAt:
            column: expires_at
            type: datetime
            nullable: true
        confirmationToken:
            column: confirmation_token
            type: string
            nullable: true
        passwordRequestedAt:
            column: password_requested_at
            type: datetime
            nullable: true
        roles:
            column: roles
            type: array
        credentialsExpired:
            column: credentials_expired
            type: boolean
        credentialsExpireAt:
            column: credentials_expire_at
            type: datetime
            nullable: true
    oneToMany:
        messages:
            targetEntity: Message
            mappedBy: user
    manyToMany:
        chats:
            targetEntity: Chat
            inversedBy: users
            joinTable:
               name: x_users_chats
               joinColumns:
                    user_id:
                        referencedColumnName: user_id
               inverseJoinColumns:
                   chat_id:
                        referencedColumnName: chat_id
    lifecycleCallbacks: {  }