gpaket:
    resource: "@GpaketBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin/manage/
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"