gpaket:
    resource: "@GpaketBundle/Resources/config/routing.yml"
    prefix:   /

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /panel/
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"